# Generated by Django 5.2.5 on 2025-08-21 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolex_Number',
            fields=[
                ('No_id', models.AutoField(primary_key=True, serialize=False)),
                ('Today_Number', models.IntegerField()),
                ('Sign', models.CharField(choices=[('WAIT', 'WAIT'), ('END', 'END'), ('DECLARE', 'DECLARE'), ('CLOSE', 'CLOSE')], max_length=7)),
                ('Description', models.TextField(max_length=50)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Upload_to', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
