# Generated by Django 5.2.5 on 2025-08-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rolex_number_month_rolex_number_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolex_number',
            name='Created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='rolex_number',
            name='Upload_to',
            field=models.DateTimeField(editable=False),
        ),
    ]
