# Generated by Django 5.2.5 on 2025-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_rolex_number_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolex_number',
            name='Created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rolex_number',
            name='Upload_to',
            field=models.DateTimeField(),
        ),
    ]
